### ISSUE TITLE
Links>>Download latest firmware gives 404

### ISSUE THREAD

**Issue by ramrattle** [4refr0nt/ESPlorer#16]
clicking links >> Download latest firmware takes me to this 404 page 

https://github.com/nodemcu/nodemcu-firmware/blob/master/pre_build/latest/nodemcu_latest.bin?raw=true

Its really confusing newbie's like me, can someone fix this

**Comment by 4refr0nt** [comment]
Hi!

Of course, new link is https://github.com/nodemcu/nodemcu-firmware/releases

It will be fix in future releases.

Thanks!


2015-09-12 10:50 GMT+05:00 ramkumar <notifications@github.com>:

**Comment by ramrattle** [comment]
Thanks for the quick reply
