### ISSUE TITLE
JComboBox Port to small

### ISSUE THREAD

**Issue by 3s1d** [4refr0nt/ESPlorer#2]
Hi,

I developed something similar, but stop the minute I saw this project! Really great work. HUGE thumbs up!

I've just to minor issues:
-On Mac or Linux the serial ports are named like this: /dev/tty.usbserial-A4001Ib9. This does not fit into the combobox and you have to sort of guess which one is the right.
-You could set a relative working directory or leave it blank. C:\... does not exist on none-M$ machines.

Keep on developing.
Thanks
Juergen

**Comment by 4refr0nt** [comment]
#2 close
