### ISSUE TITLE
http://esp8266.ru/ESPlorer is offline

### ISSUE THREAD

**Issue by confile** [4refr0nt/ESPlorer#20]
http://esp8266.ru/ESPlorer is offline

**Comment by steffimueller** [comment]
+1 @4refr0nt Could you please bring the page back online. Thank you. You did a great job.

**Comment by 4refr0nt** [comment]
Can you test http://esp8266.ru/ESPlorer/ outside Russia for closing this issue?

**Comment by marcelstoer** [comment]
Works for me.
