### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by confile** [4refr0nt/ESPlorer#24]
Could you please describe how to build ESPlorer from source?

**Comment by 4refr0nt** [comment]
You can open source as project in NetBeans IDE

**Comment by devyte** [comment]
I have the same question, I can't for the life of me figure out how to build from source in netbeans. I keep getting the error that the jssc and rsyntaxtext libs can't be found, and I don't know how to add them manually.

**Comment by devyte** [comment]
I've put these instructions, along with some step-by-step getting started stuff, in the nodemcu-platform wiki [here](https://github.com/devyte/nodemcu-platform/wiki).
