### ISSUE TITLE
send a ctrl-c (micropython)

### ISSUE THREAD

**Issue by ideal2545** [4refr0nt/ESPlorer#30]
hi, I can't seem to figure out how to send a ctrl-c to terminate a running process, how can I do this?

**Comment by 4refr0nt** [comment]
For terminate sending, please press `Send To ESP` button again

**Comment by ideal2545** [comment]
No luck, it doesnt terminate running proccess - is there a way to create a snippet to send "CTRL-C" ?

**Comment by 4refr0nt** [comment]
sorry, no

**Comment by ideal2545** [comment]
Thanks for the prompt response! I'm loving this great app. Please consider adding that functionality in the future!

Thx
Jon

**Comment by fbraghiroli** [comment]
Hi,
I found a workaround to send "ctrl-c" escape sequence by saving the '\x03' char to a free 'snippet' slot.
Steps (tested on ubuntu linux)
1) open text editor (gedit)
2) press ctrl+shift+u and type 03 (this produces a single char that has 0x03 as hex value)
3) copy this char to a new snippet
4) each time you have to send ctrl-c, simply call the snippet just saved
