### ISSUE TITLE
Allow custom key combinations for code autocomplete

### ISSUE THREAD

**Issue by Arnie97** [4refr0nt/ESPlorer#35]
In a Chinese environment, the `Ctrl` + `Space` hotkey is a global hotkey preserved for toggling the Chinese input method.  Hence the autocomplete cannot be triggered when the default key combination is pressed.

**Comment by 4refr0nt** [comment]
You can change hotkey in source code. See https://github.com/4refr0nt/ESPlorer/tree/master/ESPlorer/src/org/fife/ui/autocomplete

**Comment by Arnie97** [comment]
@4refr0nt I've found the relevant code here:
https://github.com/4refr0nt/ESPlorer/blob/master/ESPlorer/src/org/fife/ui/autocomplete/AutoCompletion.java#L366-L370
Thanks for your help.
