### ISSUE TITLE
Line Endings not preserved in Python code

### ISSUE THREAD

**Issue by fuzzyhandle** [4refr0nt/ESPlorer#40]
When a Python file is sent to ESP Flash, the line feeds are getting removed. This results in an invalid python file.

The file uploaded via Esplorer looks like
['def main():  print ("Hello Main2")print(\'Hello Main 1\')main()'] 

The same file uploaded via WebRepl looks like
['def main():\n', '  print ("Hello Main2")\n', '\n', "print('Hello Main 1')\n", 'main()']

As you can see the "\n" chars are getting removed when sending via esplorer.

Sample python code in main.py

```
def main():
  print ("Hello Main2")

print('Hello Main 1')
main()
```

**Comment by 4refr0nt** [comment]
#44

**Comment by fuzzyhandle** [comment]
Can you "release" a new version and get a pre built binary published? I think this fix will help all micropython developers.
