### ISSUE TITLE
ESplorer v0.2.0-rc5 no longer autodetects AT firmware of ESP-01

### ISSUE THREAD

**Issue by gknauf** [4refr0nt/ESPlorer#41]
I'm using ESP-01 modules with an [USB-CH340 adapter](http://plaintron.onlinetoolbox.de/ESP01USB-CH340_02-600x480.jpg); since v0.2.0-rc5 (binary downloaded as v0.2.0-rc6 from your site, but title bar and About dialog names it v0.2.0-rc5) the autodetection of the AT firmware of my ESP-01 modules does no longer work; when I switch back to v0.2.0-rc3 then my modules are properly detected again; modules have:
AT version:0.40.0.0(Aug  8 2015 14:45:58)
AT version:0.60.0.0(Jan 29 2016 15:10:17)

**Comment by dunk8888** [comment]
doesnt detect firmware of nodemcu 0.9 eather nore does the r6 version,it comes up with flash errors Communication with MCU..Got answer! Communication with MCU established. AutoDetect firmware...  AT-based firmware detected. read: r=1 at 4070D000 ERROR in flash_read: r=1 at 4070E000 ERROR in flash_read: r=1 at 4070F000
flash_read: r=1 at 4070F001 and so on and so on

**Comment by dunk8888** [comment]
its serial problem i think,i only get errors output when i change baurd rate to 9600 or i get nothing?? please help

**Comment by dunk8888** [comment]
but works fine on r2 version of esplorer

**Comment by oddstr13** [comment]
Does not detect Micropython either. This is true for both trunk and the rc5/rc6 binary.
![screenshot](https://thoas.feralhosting.com/oddstr13/sharex/image/java_2017-04-28_19-21-43.png)
The random characters you see is the ESP boot log, at a different baud rate.
