### ISSUE TITLE
missing newline on esp

### ISSUE THREAD

**Issue by FreakErn** [4refr0nt/ESPlorer#46]
I am new to programming esp's
When i send my micropython code to the ESP (ESP-01) i see that he is sending each line like this:

```
f = open('main.py', 'w')
f.write('import fancyStuff')
f.write('do fancyStuff')
f.close();
```

This result in a oneliner because there is no \n at the end of each line.
When i execute `print([x for x in open('main.py').readlines()])`
i get this: `['import fancyStuffdo fancyStuff']`

Do i have to put a "\n" in each line of my sourcecode to get newlines on my esp?

**Comment by 4refr0nt** [comment]
Fixed #40, but binaries not publish yet
