### ISSUE TITLE
Bug in file saving process

### ISSUE THREAD

**Issue by jurgis213** [4refr0nt/ESPlorer#58]
IDE doesn't write LUA file lines to memory
for some reason it uses (file.writeline) command instead of (file.write)

**Example:**

> file.remove("test.lua");
> file.open("test.lua","w+");
> w = file.writeline
w([==[print("Test")]==]);
file.close();
dofile("test.lua");
stdin:1: attempt to call field 'writelinew' (a nil value)
stack traceback:
	stdin:1: in main chunk
>

**Comment by xiongbinsh** [comment]
sure, could resolved by add ';' after the line w=file.writeline
created a PR https://github.com/4refr0nt/ESPlorer/pull/60/files  for it.
