### ISSUE TITLE
Can't Open ESPlorer.jar file

### ISSUE THREAD

**Issue by salmanfarisvp** [4refr0nt/ESPlorer#73]
I can't open  ESPlorer.jar file ,
```
java .\esp.jar
Error: Could not find or load main class .\esp.jar
Caused by: java.lang.ClassNotFoundException: /\esp/jar
```
Machine :- Windows 10
Windows PowerShell

**Comment by pdisner** [comment]
Im also having trouble finding the executable jar file to open the software. Im new to 8266 boards/node MCU but have been able to setup this app before.
