### ISSUE TITLE
Build .jar files

### ISSUE THREAD

**Issue by eliabieri** [4refr0nt/ESPlorer#9]
Could you build the .jar file for the new beta or give me a short instruction how I can do it on my own?
Thank You!

**Comment by 4refr0nt** [comment]
This beta version not really working (only new GUI prototype and partial functionality) But u can download https://github.com/4refr0nt/ESPlorer/blob/master/ESPlorer/dist/ESPlorer.jar?raw=true

**Comment by confile** [comment]
@4refr0nt There is no dist folder.
